ALTER TABLE datn.mau_sac DROP COLUMN TRANG_THAI;
ALTER TABLE datn.chat_lieu DROP COLUMN TRANG_THAI;
ALTER TABLE datn.kieu_dang DROP COLUMN TRANG_THAI;
ALTER TABLE datn.thuong_hieu DROP COLUMN TRANG_THAI;
ALTER TABLE datn.danh_muc DROP COLUMN TRANG_THAI;
ALTER TABLE datn.kich_thuoc DROP COLUMN TRANG_THAI;
-- Bỏ trạng thái do không có ý nghĩa
